### ISSUE TITLE
Getting error "Can not provide API key in the browser without "dangerouslyAllowAPIKeyInBrowser" set to true" in relay server

### ISSUE THREAD

**Issue by braunale** [openai/openai-realtime-console#26]
When using the relay server as described in the readme and clicking on connect, the relay server crashes with the following error: 

Error: Can not provide API key in the browser without "dangerouslyAllowAPIKeyInBrowser" set to true
    at new RealtimeAPI (file:///c:/dev/openai-realtime-console/node_modules/@openai/realtime-api-beta/lib/api.js:19:15)
    at new RealtimeClient (file:///c:/dev/openai-realtime-console/node_modules/@openai/realtime-api-beta/lib/client.js:222:21)
    at RealtimeRelay.connectionHandler (file:///c:/dev/openai-realtime-console/relay-server/lib/relay.js:35:20)
    at WebSocketServer.emit (node:events:520:28)
    at WebSocketServer.completeUpgrade (c:\dev\openai-realtime-console\node_modules\ws\lib\websocket-server.js:436:5)
    at WebSocketServer.handleUpgrade (c:\dev\openai-realtime-console\node_modules\ws\lib\websocket-server.js:344:10)
    at Server.upgrade (c:\dev\openai-realtime-console\node_modules\ws\lib\websocket-server.js:119:16)
    at Server.emit (node:events:520:28)
    at onParserExecuteCommon (node:_http_server:948:14)
    at onParserExecute (node:_http_server:849:3)

OS: Windows 11
Node version v22.4.1

This error is  thrown in execution of line 35 in relay.js: 
`const client = new RealtimeClient({apiKey: this.apiKey});`

It seems that this error should be thrown when using the client directly in the browser. However the error is thrown in the relay-server which does not run in the browser. I did no changed the code in any way. 

Adding the "dangerouslyAllowAPIKeyInBrowser" fixed the issue...
```
const client = new RealtimeClient({
      apiKey: this.apiKey,
      dangerouslyAllowAPIKeyInBrowser: true,
    });
```
... however it is confusing and misleading to use this in the relay server. How does the client detects if it is used in the browser or on the server?

**Comment by fred1433** [comment]
I have it also

**Comment by khorwood-openai** [comment]
Hey there! Should be fixed: https://github.com/openai/openai-realtime-api-beta/commit/2474cfe27e03c46224922bef4348cc73ff54b461

Just do `npm i openai/openai-realtime-api-beta --save` and it should update to the latest client package.
