### ISSUE TITLE
Error: Could not connect to "wss://api.openai.com/v1/realtime"

### ISSUE THREAD

**Issue by Glavin001** [openai/openai-realtime-console#4]
When I start app and provide my OpenAI API Key I see the following:

![image](https://github.com/user-attachments/assets/7d0d941e-1d8b-4802-83e2-8e0eddcd7dd4)

Apologies if the realtime API is simply not released yet. If so, at least others having the same error will see this issue and wait with me. So excited, thank you!

**Comment by arthur-brainchain** [comment]
You need to make changes to the code to get it to work, they made it like an exercise I'm guessing

**Comment by Ashoka74** [comment]
same issue

**Comment by Glavin001** [comment]
Confirmed, missing model access:

> rolling out throughout the week!
- [Keith](https://x.com/keithwhor/status/1841186962230952372)

**Comment by tschellenbach** [comment]
same issue

**Comment by mmtmn** [comment]
I've heard rumors that it might be released at 3pm Pacific Daylight Time, so 2h and 20 minutes from now

**Comment by Vicopem01** [comment]
same issue

**Comment by imWildCat** [comment]
I was able to connect for about ~15 mins but now the same, no connection

**Comment by aziz-ullah-khan** [comment]
![image](https://github.com/user-attachments/assets/e221d3f0-e1d9-4ac4-90e4-d5d0b3492d40)
 Facing the issue!

**Comment by mtkociuba** [comment]
+1

**Comment by henrygilbert22** [comment]
+1

**Comment by po0ya** [comment]
same here

**Comment by yagudaev** [comment]
The same error regardless if you use the browser or relay server. Note websocket is reachable but auth fails in `finishRequest`. So the OpenAI server is not accepting our API keys yet for some reason (maybe a gradual rollout?).

```typescript
// src/lib/realtime-api-beta/lib/api.js
// ...
const ws = new WebSocket(
  'wss://api.openai.com/v1/realtime?model=gpt-4o-realtime-preview-2024-10-01',
  [],
  {
    finishRequest: (request) => {
      // Auth
      request.setHeader('Authorization', `Bearer ${this.apiKey}`);
      request.setHeader('OpenAI-Beta', 'realtime=v1');
      request.end();
    },
  }
);
```

**Comment by AntiQuality** [comment]
ever worked at around 12:15pm PDT 😢

**Comment by jusitnl994** [comment]
got so excited! 
<img width="1077" alt="image" src="https://github.com/user-attachments/assets/cc6232dd-8ece-491c-a7de-303b0b95de63">

**Comment by laosuan** [comment]
same issue

**Comment by imWildCat** [comment]
fake status page: https://status.openai.com
real status page: https://github.com/openai/openai-realtime-console/issues/4

**Comment by KazuSh1geru** [comment]
+1

**Comment by KazuSh1geru** [comment]
same here

**Comment by MattPRD** [comment]
Me over here just trying to have cursor and o1 fix this

**Comment by YutoYasunaga** [comment]
<img width="933" alt="image" src="https://github.com/user-attachments/assets/dcacaa96-41c0-4e75-9d79-723f49c00f1e">

Same here :(

**Comment by mtkociuba** [comment]
> Me over here just trying to have cursor and o1 fix this

some one at openai right now is spamming o1 to get a fix out haha

**Comment by MattPRD** [comment]
> > Me over here just trying to have cursor and o1 fix this
> 
> some one at openai right now is spamming o1 to get a fix out haha

Everyone is at the devday after party 😭

**Comment by longseespace** [comment]
Same. Cannot connect :(

**Comment by wade-liwei** [comment]
Same. Cannot connect :(

**Comment by hambuger** [comment]
+1

**Comment by shaojun** [comment]
+1

**Comment by dabeljo** [comment]
Is there somewhere a status page to check. Its still not working.

**Comment by someshfengde** [comment]
there's this error 
```
Could not connect to "wss://api.openai.com/v1/realtime"
    at WebSocket.connectionErrorHandler (http://localhost:3000/static/js/bundle.js:57849:18)

```

If you dismiss it further you get this error 
```
ERROR
RealtimeAPI is not connected
    at RealtimeAPI.send (http://localhost:3000/static/js/bundle.js:57956:13)
    at RealtimeClient.appendInputAudio (http://localhost:3000/static/js/bundle.js:58619:21)
    at WavRecorder._chunkProcessor (http://localhost:3000/static/js/bundle.js:775:45)
    at processor.port.onmessage (http://localhost:3000/static/js/bundle.js:60409:18)
```

**Comment by NordaccaX** [comment]
Newbie here with no volume of api calls to show for. Will api still be available or just level 5 and above as usual?

**Comment by setouchi-h** [comment]
same issue. what is `paid tiers`?

![image](https://github.com/user-attachments/assets/ca4b2845-c527-4f60-853b-43ed33d5a28d)

**Comment by SubPhaser** [comment]
Can someone give some information on when this will be available for testing?

**Comment by elebumm** [comment]
> same issue. what is `paid tiers`?
> 
> ![image](https://private-user-images.githubusercontent.com/113189196/372845889-ca4b2845-c527-4f60-853b-43ed33d5a28d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NzU5NjMsIm5iZiI6MTcyNzg3NTY2MywicGF0aCI6Ii8xMTMxODkxOTYvMzcyODQ1ODg5LWNhNGIyODQ1LWM1MjctNGY2MC04NTNiLTQzZWQzM2Q1YTI4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxMzI3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmM0ZTBmOGNiNDRmY2YwM2Y4YjBlMmJkZDA3Njc3OGY0YTBjZGRiNTZmOTI0YmFkZmFkNzk5YjQyNTg2ZjUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8cIzNXNbMJFoKbfdQ2oI5HsD7Con5-3q3QDLYu_M1Wc)

I believe it refers to API users who have paid for credits.

This works in tier systems as well (e.g $100 / month, $1000 / month etc)

**Comment by mmtmn** [comment]
> Can someone give some information on when this will be available for testing?

rumor has it that someone asked an employee and they said we should have access in 1-2 days

**Comment by jamesfebin** [comment]
Same issue

**Comment by tdambrowitz** [comment]
> > Can someone give some information on when this will be available for testing?
> 
> rumor has it that someone asked an employee and they said we should have access in 1-2 days

That was [me](https://community.openai.com/t/realtime-websocket-error-unexpected-server-response-403/963947/38?u=trenton.dambrowitz) on the OpenAI Dev Forum, this is what I was told:

> RealTime API is being released in phases so you should gain access over the next day or two! Looking forward to hearing what you build when you get your hands on it!

**Comment by srhise** [comment]
Maybe we can all port this app from CRA to Next.js in the meantime while we wait for us to be able to actually connect to the API :)

**Comment by navjotdhanawat** [comment]
Currently the access is given to Tier 3 users (100 usd and more)
https://platform.openai.com/docs/guides/rate-limits/usage-tiers

**Comment by jusitnl994** [comment]
> uides/rate-limits/usage-tiers

Tier 3 user here, no access to this model yet

**Comment by MattPRD** [comment]
(Tier 5 here, I dont have it yet either)

Once its out I'll race you all to build something though.

**Comment by mtkociuba** [comment]
> (Tier 5 here, I dont have it yet either)
> 
> Once its out I'll race you all to build something though.

the race is legitimately on. the amount of low hanging fruit to pick over the next few months

**Comment by dsmurrell** [comment]
Same here. Would love access to this model :)

Could not connect to "wss://api.openai.com/v1/realtime"
    at WebSocket.connectionErrorHandler (http://localhost:3000/static/js/bundle.js:59604:18)

**Comment by imWildCat** [comment]
I unsubscribed to this thread.

PSA:
open this page https://platform.openai.com/playground/realtime
if it is like
<img width="836" alt="image" src="https://github.com/user-attachments/assets/c9188307-6c4e-4389-8e21-decd3112f032">

that means you don't have the access.

no need to post because it is clearly by design from OpenAI and they don't care our small customers.

**Comment by gastonmorixe** [comment]
Same issue here, neither web nor relay server work. Both failing with 403. 
The model `gpt-4o-realtime-preview-2024-10-01` is also missing from the my dev model  list API response.

<img width="758" alt="image" src="https://github.com/user-attachments/assets/f52d29a6-c00a-4c8e-9e86-d2d5265d8deb">

**Comment by MarceloTerra0** [comment]
![image](https://github.com/user-attachments/assets/f6e24e48-a4f3-4ab1-a406-2ce8c57a945a)

It's not that openai doesn't care about small accounts!. My work's organization is a tier 5 org and we still don't have access to it!! (For comparison, we got access to o1-preview the day it released)

**Comment by nevercast** [comment]
I'm Tier 4 - its just not rolled out to everyone yet. We'll have to wait.

**Comment by Mcxgamecaster** [comment]
damn what a false hype

**Comment by meetuljain** [comment]
I am on tier-5. It is not available for me either.

**Comment by michael7908** [comment]
same issue.

**Comment by jamesfebin** [comment]
I got it working through Azure, [they provide the same API](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/audio-real-time). 

Just an FYI if you expect it to respond like ChatGPT's advanced voice mode you will be disappointed.

**Comment by SuperDisk** [comment]
I can confirm you can get it going on Azure even if you don't have access via OpenAI yet. That said, this whole thing seems to just be the old-style TTS voice which can respond in real-time, it's *not* the advanced voice mode. Pretty disappointing.

https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/audio-real-time

**Comment by arthur-brainchain** [comment]
i hear the most you post on this channel the faster you get access

**Comment by wiselancer** [comment]
Having the same issue :(

**Comment by arthurgervais** [comment]
+1

**Comment by utsavsinghal5** [comment]
I am tier 5 in enterprise. It should be enabled now at least??

**Comment by ArticSeths** [comment]
> I can confirm you can get it going on Azure even if you don't have access via OpenAI yet. That said, this whole thing seems to just be the old-style TTS voice which can respond in real-time, it's _not_ the advanced voice mode. Pretty disappointing.
> 
> https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/audio-real-time

so this is false?

![image](https://github.com/user-attachments/assets/f7dadb30-e4d0-467c-8d11-7f5bdd31fd16)

https://openai.com/index/introducing-the-realtime-api/#:~:text=The%20Realtime%20API%20is%20built%20on%20the%20same%20version%20of%20GPT%2D4o%20that%20powers%20Advanced%20Voice%20Mode%20in%20ChatGPT

**Comment by SuperDisk** [comment]
@ArticSeths Yeah, I think it's just false, unless the underlying model is the same but it's some outer layer that differs. The real-time API isn't nearly as powerful as advanced voice mode. You can basically achieve the same results as the real-time API by piping GPT-4o output into their TTS endpoint, it's just slower.

**Comment by mr-haseeb** [comment]
By when we are expecting resolution to the issue?

**Comment by bytewiz** [comment]
I am Tier 2 and no access yet  🙌

**Comment by SuperDisk** [comment]
In case anyone wants to see it in action: https://www.youtube.com/watch?v=SltXpjGYWvc

**Comment by BFergerson** [comment]
> @ArticSeths Yeah, I think it's just false, unless the underlying model is the same but it's some outer layer that differs. The real-time API isn't nearly as powerful as advanced voice mode. You can basically achieve the same results as the real-time API by piping GPT-4o output into their TTS endpoint, it's just slower.
> 
> Judging by the way the API is defined and their marketing for it, my guess is that this was originally supposed to launch with advanced voice mode-like capabilities, then was nerfed late in development to use their older tech, either for business or technical reasons. My (again) guess is that they'll update the real-time API to have the advanced features at some later point, seeing as all the infrastructure is there API wise. That's just my intuition though, take it with a grain of salt.

I'm currently playing around with the Realtime API via Azure for https://github.com/voqal/voqal and this is definitely not the standard OpenAI TTS model. It can yell, whisper, sing, etc.

Here is an example of it singing (Happy birthday to SuperDisk): https://jumpshare.com/s/AqlSfo4c8TImGIWleNcw

> Note: Audio is a bit messed up. Still figuring out how to use it.

---


> In case anyone wants to see it in action: https://www.youtube.com/watch?v=SltXpjGYWvc

I got that result when I used their example application too. Maybe they haven't fully updated it?

**Comment by SuperDisk** [comment]
Interesting, I guess you're right since I can't make the stock TTS model do the singing or whispering, but I think you'll concur that this is definitely not advanced voice, which can (according to the demos) sing on pitch and do a multitude of accents when you ask. In fact in a different recording of the "italian accent" thing it actually reads "It's-a me" as "It's A me" like the letter A. So I think it is just interpreting text rather than being truly speech-to-speech.

**Comment by thejackwu** [comment]
I also have access to the Realtime API on Azure and spent some time playing around with it. But it doesn't perform as well as ChatGPT's Advanced voice mode in my opinion, especially on switching between difference languages. Not sure if that's what OpenAI is working on fixing before the official launch.

**Comment by BFergerson** [comment]
> Interesting, I guess you're right since I can't make the stock TTS model do the singing or whispering, but I think you'll concur that this is definitely not advanced voice, which can (according to the demos) sing on pitch and do a multitude of accents when you ask. In fact in a different recording of the "italian accent" thing it actually reads "It's-a me" as "It's A me" like the letter A. So I think it is just interpreting text rather than being truly speech-to-speech.

I feel like it's doing speech-to-speech since the whisper-1 translation it's giving sometimes differs from what it responds with when I give it the instructions "Repeat exactly what I say". The transcription will be words off but the audio will be spot on.

Here is it saying "It's-a me Mario": https://jumpshare.com/s/riDS6Y3ObSQyiue0ze6g

Is that correct?

**Comment by lgandecki** [comment]
@BFergerson: I think you are right, it's definitely confusing that they use whisper in their example. They should just skip that.
The understanding is much better than the text transcription would suggest. But it seems strangely like text to voice using whisper from their side.
Could you show some code of how are you using it, which is clearly different from the Azure example?

But so far, huge confusion, bad communication (released today! .. 2 days later - crickets), terrible code examples

**Comment by BFergerson** [comment]
5b8c7c1e5d8d46cda076bd7a7d1c9d1b

> @BFergerson: I think you are right, it's definitely confusing that they use whisper in their example. They should just skip that. The understanding is much better than the text transcription would suggest. But it seems strangely like text to voice using whisper from their side. Could you show some code of how are you using it, which is clearly different from the Azure example?
> 
> But so far, huge confusion, bad communication (released today! .. 2 days later - crickets), terrible code examples
> 
> edited: Actually, playing with it a bit more.. It does seem like now that it can sing, talk faster/slower. Earlier today it definitely did NOT do that. But still, it's so much more stiff than the advanced voice.. Investigating now..
> 
> edited2: And now, it just reads the lines it's supposed to sing.. So weird. Hopefully this is just buggy! I guess I will start programming assuming this all will be improved soon

I can confirm I can get their example app to sing as well.

**Comment by ibehnam** [comment]
still not working for me (tier 4).

**Comment by ibehnam** [comment]
@lgandecki what's your problem?

**Comment by lgandecki** [comment]
@ibehnam those comments won't help, OpenAI surely knows this is not rolled out, it's not like they are going to open this issue thread and just because of your comment go "Oh shoot! We forgot to release it!" :) It would be more interesting to hear from people that DID get access. But, till then, azure works - although things seem off

**Comment by ibehnam** [comment]
I provided some info about my tier so people know it's probably not a tier issue.

**Comment by SuperDisk** [comment]
@BFergerson For comparison here's ChatGPT advanced voice doing Mario: https://vocaroo.com/1fAf3jYUytbX

**Comment by BFergerson** [comment]
> @BFergerson For comparison here's ChatGPT advanced voice doing Mario: https://vocaroo.com/1fAf3jYUytbX

I can get it somewhat similar using the example app (even does the wahoo!), but yours is a bit better. I think that is just a voice model issue though. The only models currently available for Realtime API are these: https://platform.openai.com/docs/guides/text-to-speech/voice-options

I see that there are different named voices for advanced voice mode. My guess is we will eventually get access to those too.

**Comment by lgandecki** [comment]
@BFergerson  that's confusing is that those voice models are the ones from text-to-speech whisper, and from the previous (non-"advanced") voice mode. 
There were voice actors that were used to train the new voices, and it doesn't seem reasonable to expect that the old text-to-speech whisper models would suddenly start to sing or speak in different accents? 
Even though, they sometimes do.. but way worse than what advanced voice mode does basically every time.
I'm trying to play with the system message but that's not really helping much

**Comment by tdambrowitz** [comment]
> @BFergerson that's confusing is that those voice models are the ones from text-to-speech whisper, and from the previous (non-"advanced") voice mode. There were voice actors that were used to train the new voices, and it doesn't seem reasonable to expect that the old text-to-speech whisper models would suddenly start to sing or speak in different accents? Even though, they sometimes do.. but way worse than what advanced voice mode does basically every time. I'm trying to play with the system message but that's not really helping much

Remember [Voice Engine](https://openai.com/index/navigating-the-challenges-and-opportunities-of-synthetic-voices/), the thing they kept internal that could replicate anyone's voice in any language saying anything?

I reckon they've just used the large amount of training data they had from those people to train these new Realtime API voices

**Comment by BFergerson** [comment]
> @BFergerson that's confusing is that those voice models are the ones from text-to-speech whisper, and from the previous (non-"advanced") voice mode. There were voice actors that were used to train the new voices, and it doesn't seem reasonable to expect that the old text-to-speech whisper models would suddenly start to sing or speak in different accents? Even though, they sometimes do.. but way worse than what advanced voice mode does basically every time. I'm trying to play with the system message but that's not really helping much

I would have thought the same thing but maybe they've got enough data on the old voices to automatically upgrade them to a newer model? We are talking about synthesized speech here. 

---



> > that's confusing is that those voice models are the ones from text-to-speech whisper, and from the previous (non-"advanced") voice mode. There were voice actors that were used to train the new voices, and it doesn't seem reasonable to expect that the old text-to-speech whisper models would suddenly start to sing or speak in different accents? Even though, they sometimes do.. but way worse than what advanced voice mode does basically every time. I'm trying to play with the system message but that's not really helping much
> 
> Remember [Voice Engine](https://openai.com/index/navigating-the-challenges-and-opportunities-of-synthetic-voices/), the thing they kept internal that could replicate anyone's voice in any language saying anything?
> 
> I reckon they've just used the large amount of training data they had from those people to train these new Realtime API voices

Yeah, basically this.

**Comment by lgandecki** [comment]
Why would they upgrade the older model/older synthesised speech to the new model, and basically end up with worse product? God, I wish so much this was just a bug! But the wording on their site pretty clearly states in a few places that this is "LIKE" or "SIMILAR" to advanced voice mode, not really "it"

Btw, I personally couldn't care less about singing. But I care about:
a) it seeming like it REALLY understands. My tone of voice, emotions, my accent, and so on.
b) it seeming like an expressive, human-like companion. So the voice also has to have emotions that are relevant to the context... Currently it seems very artificial.. The Advanced mode feels like it knows what it's doing. This realtime api would "think" it's singing, while it's just reading text out loud. It's like something between text to speech (old voice mode) and speech to speech (advanced voice mode).

**Comment by lgandecki** [comment]
I mean, I think you guys might be right. But I don't understand why would they do this? Unless they wanted to release a worse product? Or unless this one was much cheaper to run?

**Comment by BFergerson** [comment]
> Why would they upgrade the older model/older synthesised speech to the new model, and basically end up with worse product? God, I wish so much this was just a bug! But the wording on their site pretty clearly states in a few places that this is "LIKE" or "SIMILAR" to advanced voice mode, not really "it"
> 
> Btw, I personally couldn't care less about singing. But I care about: a) it seeming like it REALLY understands. My tone of voice, emotions, my accent, and so on. b) it seeming like an expressive, human-like companion. So the voice also has to have emotions that are relevant to the context... Currently it seems very artificial.. The Advanced mode feels like it knows what it's doing. This realtime api would "think" it's singing, while it's just reading text out loud. It's like something between text to speech (old voice mode) and speech to speech (advanced voice mode).

I don't know why but their documentation clearly states:

> [How can I control the emotional range of the generated audio?](https://platform.openai.com/docs/guides/text-to-speech/how-can-i-control-the-emotional-range-of-the-generated-audio)
There is no direct mechanism to control the emotional output of the audio generated. Certain factors may influence the output audio like capitalization or grammar but our internal tests with these have yielded mixed results.

And I can confirm without a doubt that that's no longer true. Even with those older models.

**Comment by lgandecki** [comment]
hmm.. wouldn't you say that we get "mixed results" as well? To me it almost seems like an exact definition of what we see :-)

**Comment by BFergerson** [comment]
I would say it doesn't have the full emotional range as advanced voice mode. It's definitively an upgrade though. I'm already excited about using it in an upcoming OSS project for automated dubbing.

**Comment by lgandecki** [comment]
It's not just the emotional range. Like, I asked it to guess my accent. I'm Polish, and advanced voice mode does a great job - guesses it after a few sentences. It guesses Central Europe and with less confidence - Poland, is able to tell what sounds are giving me away, simulate the way I spoke (not my voice, but the sounds, melody). This one? Sometimes it guesses, but can't really say why, and a few times it actually said it can't guess, because it just seeing the text, not hearing me. 

But fair - this is a significant upgrade for a lot of usecases... Just a bit disappointing and overhyped. 
I guess we get the version 1, and OpenAI keeps the version 2 :) 
I should get to code and use what's available. Maybe they will release something better in the future.

**Comment by HatmanStack** [comment]
Also no access through the API.  I'm curious about SSML controls.  The normal TTS with OpenAI seems like it respects some of the controls.  Nothing like Google TTS that strictly adheres to SSML.  Has anybody played around with SSML controls in the instructions?

**Comment by dabeljo** [comment]
> @ibehnam those comments won't help, OpenAI surely knows this is not rolled out, it's not like they are going to open this issue thread and just because of your comment go "Oh shoot! We forgot to release it!" :) It would be more interesting to hear from people that DID get access. But, till then, azure works - although things seem off

Then please switch to a forum or discord and discuss the quality of the output, github issue tracking for sure is not the place.
OAI should communicate better here, they could at least give a timeline when will that be available. Letting us to basically F5 this page is not what i expected from them.

**Comment by lgandecki** [comment]
oh, so you'd prefer this thread was just full of +1s? Wow! 

We did discuss the quality of the output, because it seemed buggy. But I think the realization is - that's exactly what we get, which is solid, but disappointing.
I agree about the lack of communication, overhyping, lack of timelines, but how does this relate to our debugging this in public?

**Comment by njbbaer** [comment]
Thanks @lgandecki, I appreciate seeing your overview since I don't have access yet. Frankly I'm a lot less excited than I was, but we'll see what they do in time. I wonder if they're having trouble with the rollout, hence the delay.

**Comment by lgandecki** [comment]
@njbbaer thanks! 
unfortunately seeing the TERRIBLE demos from Microsoft, it looks like that's what they do plan to deliver, one example:
https://www.youtube.com/watch?v=n4R1LWvqa1k

**Comment by cmarrero01** [comment]
I am currently on Tier 5 but noticed that the model is not available in my account. Is there any guidance on resolving this issue for Tier 5 users? From my understanding, the model should be accessible, yet it isn't. Any advice would be greatly appreciated.

**Comment by lgandecki** [comment]
@cmarrero01 there is a lot of TIER 5 people here, including me, and as far as I see NO ONE has access (possibly except the guys that were in person at the dev day?). There is no guidance, and your understanding is mistaken. ;-) Just wait. Or use azure.

**Comment by cmarrero01** [comment]
@lgandecki I'd rather kill myself than use Azure, but thanks for the suggestion. We'll have to wait.

**Comment by Nghiauet** [comment]
Ok I'll wait. Hope can have access it soon.

**Comment by akshayvkt** [comment]
it finally works for me - and i'm probably tier 3

**Comment by njbbaer** [comment]
I just got access, tier 4.

**Comment by AriesAlex** [comment]
still can't use, tier 5
but looks like some people finally getting access?

**Comment by Benjoyo** [comment]
> This one? Sometimes it guesses, but can't really say why, and a few times it actually said it can't guess, because it just seeing the text, not hearing me.

Exactly, it can’t respond to or identify anything that wouldn’t be in a transcript. Plus the voices sound just ad lifeless as the standard tts voices. 

Just to check, anyone who thinks it performs well is in the EU? Or other way around, someone who thinks it is underwhelming is from outside the EU?

hope they didn’t cripple it for us.

**Comment by BFergerson** [comment]
> > This one? Sometimes it guesses, but can't really say why, and a few times it actually said it can't guess, because it just seeing the text, not hearing me.
> 
> Exactly, it can’t respond to or identify anything that wouldn’t be in a transcript. Plus the voices sound just as lifeless as the standard tts voices.
> 
> Just to check, anyone who thinks it performs well is in the EU? Or other way around, someone who thinks it is underwhelming is from outside the EU?
> 
> hope they didn’t cripple it for us.

The version OpenAI is hosting does feel nerfed. It's refusing to sing and yell whereas the Azure one obliges. Both versions feel buggy, though.

https://github.com/user-attachments/assets/cc1597f0-1713-411c-8204-63a19294e165

**Comment by Benjoyo** [comment]
> The version OpenAI is hosting does feel nerfed. It's refusing to sing and yell whereas the Azure one obliges. Both versions feel buggy, though.
> 
>  sing-birthday.mp4

Hm, I tried Azure first, when OpenAI didn’t work yet. And now playing with the OpenAI version. Both feel and sound the same to me. Was hoping Azure had something worse (although that wouldn’t have made any sense, model is supposed to be the same). 

Maybe it is just buggy and fluctuant, but I didn’t have a single conversation yet that felt „alive“. Just somewhat robotic text in, tts out.

**Comment by BFergerson** [comment]
> > The version OpenAI is hosting does feel nerfed. It's refusing to sing and yell whereas the Azure one obliges. Both versions feel buggy, though.
> > sing-birthday.mp4
> 
> Hm, I tried Azure first, when OpenAI didn’t work yet. And now playing with the OpenAI version. Both feel and sound the same to me. Was hoping Azure had something worse (although that wouldn’t have made any sense, model is supposed to be the same).
> 
> Maybe it is just buggy and fluctuant, but I didn’t have a single conversation yet that felt „alive“. Just somewhat robotic text in, tts out.

I think you're right. I tried the advanced voice mode on Android and it does have the ability to detect accents. The versions on OpenAI and Azure can not do that.

**Comment by po0ya** [comment]
works now for me! tier 4

**Comment by AriesAlex** [comment]
> still can't use, tier 5 but looks like some people finally getting access?

Finally gained access, but unfortunately, it's much worse than the official mode on the Android app.

**Comment by jamesfebin** [comment]
Integrated OpenAI's Realtime API; here's a demo.

1. Buggy and sensitive to small sounds that interrupt the conversational flow.
2. Voice still sounds robotic, unlike ChatGPT's advanced voice mode. 

https://github.com/user-attachments/assets/919982f0-321c-4968-a95d-9c53ff8b976a

**Comment by mmtmn** [comment]
issue solved. for small sounds you'd probably need to change the silence threshold, for advanced voice mode I think you'll need to use tts-2 model, which hasn't been released yet (I'm guessing this).

**Comment by Benjoyo** [comment]
> issue solved. for small sounds you'd probably need to change the silence threshold, for advanced voice mode I think you'll need to use tts-2 model, which hasn't been released yet (I'm guessing this).

No, there shouldn’t be any tts at all, it was presented as multimodal voice in, voice out. Without intermediary text. And I think it is true, only they did everything they could to make it NOT sound or behave that way for some reason.

**Comment by khorwood-openai** [comment]
Hey folks -- closing for now, access has been rolled out to all users!

**Comment by joshuadmatthews** [comment]
I am still seeing websocket errors when I try to use it.
