### ISSUE TITLE
WavRecorder Error

### ISSUE THREAD

**Issue by mohammadaminyza** [openai/openai-realtime-console#488]
Does anyone know how to solve this:

Uncaught runtime errors:
×
ERROR
Could not start media stream
    at WavRecorder.begin (http://localhost:3000/static/js/bundle.js:58542:13)
    at async http://localhost:3000/static/js/bundle.js:718:5

**Comment by mohammadaminyza** [comment]
My device didn't have a microphone, so it throw not found exception!
