### ISSUE TITLE
npm run dev # Error: Missing script: "dev"

### ISSUE THREAD

**Issue by gwpl** [openai/openai-realtime-console#498]
`npm run dev` as mentioned in README.md : https://github.com/openai/openai-realtime-console/blob/d872e76dd1f39d2ea3d1d8cebaeeddbfc8117cc7/README.md?plain=1#L22
does not work

```
$ npm install

up to date, audited 117 packages in 679ms

30 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

```
$ npm run dev
npm error Missing script: "dev"
npm error
npm error To see a list of scripts, run:
npm error   npm run
npm error A complete log of this run can be found in: /home/gw-t490/.npm/_logs/2024-12-22T21_52_04_865Z-debug-0.log

```

## cat logs:
```
$ cat /home/username/.npm/_logs/2024-12-22T21_47_34_906Z-debug-0.log
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@10.9.2
2 info using node@v20.18.1
3 silly config load:file:/usr/lib/node_modules/npm/npmrc
4 silly config load:file:/home/username/github/openai/openai-realtime-api-beta/.npmrc
5 silly config load:file:/home/username/.npmrc
6 silly config load:file:/etc/npmrc
7 verbose title npm run dev
8 verbose argv "run" "dev"
9 verbose logfile logs-max:10 dir:/home/username/.npm/_logs/2024-12-22T21_47_34_906Z-
10 verbose logfile /home/username/.npm/_logs/2024-12-22T21_47_34_906Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
12 silly logfile done cleaning log files
13 verbose stack Error: Missing script: "dev"
13 verbose stack
13 verbose stack To see a list of scripts, run:
13 verbose stack   npm run
13 verbose stack     at #run (/usr/lib/node_modules/npm/lib/commands/run-script.js:111:13)
13 verbose stack     at async RunScript.exec (/usr/lib/node_modules/npm/lib/commands/run-script.js:40:7)
13 verbose stack     at async Npm.exec (/usr/lib/node_modules/npm/lib/npm.js:207:9)
13 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli/entry.js:74:5)
14 error Missing script: "dev"
14 error
14 error To see a list of scripts, run:
14 error   npm run
15 verbose cwd /home/username/github/openai/openai-realtime-api-beta
16 verbose os Linux 6.12.3-arch1-1
17 verbose node v20.18.1
18 verbose npm  v10.9.2
19 verbose exit 1
20 verbose code 1
21 error A complete log of this run can be found in: /home/username/.npm/_logs/2024-12-22T21_47_34_906Z-debug-0.log
```

And following logs advise running `npm run`:

```
$ npm run
Lifecycle scripts included in @openai/realtime-api-beta@0.0.0:
  test
    mocha ./test/index.js
```

ok , let's try tests then:

```
$ npm test

> @openai/realtime-api-beta@0.0.0 test
> mocha ./test/index.js



  Test suite
    RealtimeAPI
      ✔ Should instantiate the RealtimeAPI with no apiKey
No apiKey provided for connection to "wss://api.openai.com/v1/realtime"
      ✔ Should fail to connect to the RealtimeAPI with no apiKey (536ms)
      ✔ Should instantiate the RealtimeAPI
      ✔ Should connect to the RealtimeAPI (650ms)
      ✔ Should close the RealtimeAPI connection

  Audio samples tests
    ✔ Should load all audio samples (60ms)
    ✔ Should instantiate the RealtimeClient
    ✔ Should connect to the RealtimeClient (822ms)
[Session ID] sess_AhOAySaYr2tChDddtkEoZ
    ✔ Should receive "session.created" and send "session.update"
    ✔ Should send an audio file about toronto (.mp3)
    ✔ Should waitForNextItem to receive "conversation.item.created" from user (550ms)
    ✔ Should waitForNextItem to receive "conversation.item.created" from assistant (703ms)
    ✔ Should waitForNextCompletedItem to receive completed item from assistant (748ms)
    ✔ Should close the RealtimeClient connection

  RealtimeClient (Browser)
    ✔ Should fail to instantiate the RealtimeClient when "dangerouslyAllowAPIKeyInBrowser" is not set
    ✔ Should instantiate the RealtimeClient when "dangerouslyAllowAPIKeyInBrowser" is set
    turn_end_mode: "client_decision"
Warning: Connecting using API key in the browser, this is not recommended
      ✔ Should connect to the RealtimeClient (598ms)
[Session ID] sess_AhOB1uAyMCUVQhZtksmys
      ✔ Should receive "session.created" and send "session.update"
      ✔ Should send a simple hello message (text)
      ✔ Should waitForNextItem to receive "conversation.item.created" from user (133ms)
      ✔ Should waitForNextItem to receive "conversation.item.created" from assistant (184ms)
      ✔ Should waitForNextCompletedItem to receive completed item from assistant (1231ms)
      ✔ Should close the RealtimeClient connection

  RealtimeClient (Node.js)
    ✔ Should instantiate the RealtimeClient
    turn_end_mode: "client_decision"
      ✔ Should connect to the RealtimeClient (595ms)
[Session ID] sess_AhOB3Qj32dPLTIoRZHvns
      ✔ Should receive "session.created" and send "session.update"
      ✔ Should send a simple hello message (text)
      ✔ Should waitForNextItem to receive "conversation.item.created" from user (135ms)
      ✔ Should waitForNextItem to receive "conversation.item.created" from assistant (371ms)
      ✔ Should waitForNextCompletedItem to receive completed item from assistant (1169ms)
      ✔ Should close the RealtimeClient connection


  31 passing (9s)
```

**Comment by kwhinnery-openai** [comment]
Confirming `npm run dev` works on both Mac and Windows in the most recent version on `main` - would be worth giving it another try. Thanks!
