### ISSUE TITLE
Compilation error during build

### ISSUE THREAD

**Issue by arun2k17** [openai/openai-realtime-console#502]
I am getting a compilation error when pulling the main branch locally and running it.

error during build:
Could not resolve "<local file path>/client/pages/index.jsx" from "../../../../:routes.js"
file: /:routes.js

I could not find the file routes.js in the source

**Comment by akayalEC** [comment]
I am also getting following same error...

> node server.js --dev

4:52:55 pm [vite] Pre-transform error: Failed to load url ./Amit/opencv-realtime_console/openai-realtime-console/C:/Amit/opencv-realtime_console/openai-realtime-console/client/pages/index.jsx (resolved id: ./Amit/opencv-realtime_console/openai-realtime-console/C:/Amit/opencv-realtime_console/openai-realtime-console/client/pages/index.jsx) in /:routes.js. Does the file exist?
4:52:55 pm [vite] Error when evaluating SSR module /:routes.js:
|- Error: Failed to load url ./Amit/opencv-realtime_console/openai-realtime-console/C:/Amit/opencv-realtime_console/openai-realtime-console/client/pages/index.jsx (resolved id: ./Amit/opencv-realtime_console/openai-realtime-console/C:/Amit/opencv-realtime_console/openai-realtime-console/client/pages/index.jsx) in /:routes.js. Does the file exist?
    at loadAndTransform (file:///C:/Amit/opencv-realtime_console/openai-realtime-console/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:51920:17)
    at async instantiateModule (file:///C:/Amit/opencv-realtime_console/openai-realtime-console/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52874:44)

4:52:55 pm [vite] Error when evaluating SSR module C:\Amit\opencv-realtime_console\openai-realtime-console\client\index.js:
|- Error: Failed to load url ./Amit/opencv-realtime_console/openai-realtime-console/C:/Amit/opencv-realtime_console/openai-realtime-console/client/pages/index.jsx (resolved id: ./Amit/opencv-realtime_console/openai-realtime-console/C:/Amit/opencv-realtime_console/openai-realtime-console/client/pages/index.jsx) in /:routes.js. Does the file exist?
    at loadAndTransform (file:///C:/Amit/opencv-realtime_console/openai-realtime-console/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:51920:17)
    at async instantiateModule (file:///C:/Amit/opencv-realtime_console/openai-realtime-console/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52874:44)

node:internal/modules/run_main:122
    triggerUncaughtException(
    ^

Error: Failed to load url ./Amit/opencv-realtime_console/openai-realtime-console/C:/Amit/opencv-realtime_console/openai-realtime-console/client/pages/index.jsx (resolved id: ./Amit/opencv-realtime_console/openai-realtime-console/C:/Amit/opencv-realtime_console/openai-realtime-console/client/pages/index.jsx) in /:routes.js. Does the file exist?
    at loadAndTransform (file:///C:/Amit/opencv-realtime_console/openai-realtime-console/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:51920:17)
    at async instantiateModule (file:///C:/Amit/opencv-realtime_console/openai-realtime-console/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52874:44) {
  code: 'ERR_LOAD_URL'
}

**Comment by giannik** [comment]
same here

**Comment by mark-pearson-bluefruit** [comment]
I am also getting this error

**Comment by mark-pearson-bluefruit** [comment]
Also, similar error at https://github.com/openai/openai-realtime-console/issues/497

**Comment by MarcoPeretti** [comment]
I am getting the same error on Windows, but strangely not on my Mac.

**Comment by kwhinnery-openai** [comment]
Hi there - we recently updated this sample app with a configuration that should work on both Mac and Windows. Check out the latest version on the `main` branch and see if it is working for you. Thanks for your patience!
